---
title: "SEIRS fit to RV cases (national scale)"
output: pdf_document
date: "2025-03-19"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir="C:/Users/wb9928/OneDrive - Princeton University/Desktop/RV/Data_and_Codes")
```

```{r}
rm(list=ls())

library(tidyverse)
library(plyr)
library(lubridate)
library(cowplot)
library(ggpubr)
library(rstan)

source("Fit/Functions_fit.R")
```

# Data

```{r}
# import data
load("Data/USA/Data_USA.RData")
load("Data/Canada/data_canada_province.RData")
```

```{r}
data_us$IAV_scaled_cases_smooth <- smooth_cases(data_us)
data_ca$IAV_scaled_cases_smooth <- smooth_cases(data_ca)

plot_grid(
  
  ggplot(data_us, aes(x=date)) +
    geom_point(aes(y=IAV_scaled_cases), pch=1) +
    geom_line(aes(y=IAV_scaled_cases_smooth)),
  
  ggplot(data_ca, aes(x=date)) +
    geom_point(aes(y=IAV_scaled_cases), pch=1) +
    geom_line(aes(y=IAV_scaled_cases_smooth)),
  
  ncol=2)
```
# Stan inputs

```{r}
n_chains <- 4 # = number of cores as well
n_warmup <- 2000
n_iter <- n_warmup + 2000

n_step <- 4

eta <- 5 # approx 2.45 days for recovery
gamma <- 0.975 # approx 8 days for recovery
mu <- 1/80/52 # natural mortality

constants <- list("eta"=eta, "gamma"=gamma, "mu"=mu, "n_step"=n_step)

pop_us <- read.csv("Data/USA/State_2020_pop.csv")
pop_ca <- read.csv("Data/Canada/Canada_pop_size.csv")
```

```{r}
data_us_stan <- data_stan2(data=data_us, constants, pop=sum(pop_us$pop_2020))
data_ca_stan <- data_stan2(data=data_ca, constants, pop=pop_ca$pop_2021[pop_ca$Province=="Canada"])
```

# With potential viral interaction

```{r}
model <- stan_model("Fit/Stan_models/SEIRS/SEIRS_npi_vi.stan")
parms <- c("logbeta0", "eps_beta[1]", "eps_beta[2]", "eps_beta[3]", "eps_beta[4]", "sigma_beta",
           "kappa", "phi", "omega", "rho", "S0", "E0", "I0", "sigma")
```

------- US (national) ----------------------------------------------------------
  
```{r, eval=FALSE}
fit <- sampling(model, data=data_us_stan,
                chains=n_chains, iter=n_iter, warmup=n_warmup, seed=1001,
                control=list(adapt_delta=0.95, max_treedepth=15),
                cores=n_chains)

saveRDS(fit, "Fit/Output/fit_RV_SEIRS_npi_vi_us.RDS")
```

```{r}
fit <- readRDS("Fit/Output/fit_RV_SEIRS_npi_vi_us.RDS")

check_hmc_diagnostics(fit)
get_num_divergent(fit)
get_num_max_treedepth(fit)
get_low_bfmi_chains(fit)
get_bfmi(fit)

summary(fit)$summary[c(1:4,53:60),]
```

```{r}
posterior <- extract(fit)

traceplot(fit, pars=parms)
pairs(fit, pars=parms)
plot_fit(posterior, data_us)
plot_beta(posterior)
```

------- Canada (national) ------------------------------------------------------
  
```{r, eval=FALSE}
fit <- sampling(model, data=data_ca_stan,
                chains=n_chains, iter=n_iter, warmup=n_warmup, seed=1234,
                control=list(adapt_delta=0.95, max_treedepth=15),
                cores=n_chains)

saveRDS(fit, "Fit/Output/fit_RV_SEIRS_npi_vi_ca.RDS")
```

```{r}
fit <- readRDS("Fit/Output/fit_RV_SEIRS_npi_vi_ca.RDS")

check_hmc_diagnostics(fit)
get_num_divergent(fit)
get_num_max_treedepth(fit)
get_low_bfmi_chains(fit)
get_bfmi(fit)

summary(fit)$summary[c(1:4,53:60),]
```

```{r}
posterior <- extract(fit)

traceplot(fit, pars=parms)
pairs(fit, pars=parms)
plot_fit(posterior, data_ca)
plot_beta(posterior)
```