---
title: "SIRS fit to RV cases (USA) -- lag 5"
output: pdf_document
date: "2025-03-19"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir="C:/Users/wb9928/OneDrive - Princeton University/Desktop/RV/Data_and_Codes")
```

```{r}
rm(list=ls())

library(tidyverse)
library(plyr)
library(lubridate)
library(cowplot)
library(ggpubr)
library(rstan)
library(bridgesampling)

source("Fit/Functions_fit.R")
```

# Data

```{r}
load("Data/USA/Data_USA.RData") # import data
```

```{r}
data_us$IAV_scaled_cases <- data_us$IAV_scaled_cases_lag5
data_hhs1$IAV_scaled_cases <- data_hhs1$IAV_scaled_cases_lag5
data_hhs2$IAV_scaled_cases <- data_hhs2$IAV_scaled_cases_lag5
data_hhs3$IAV_scaled_cases <- data_hhs3$IAV_scaled_cases_lag5
data_hhs4$IAV_scaled_cases <- data_hhs4$IAV_scaled_cases_lag5
data_hhs5$IAV_scaled_cases <- data_hhs5$IAV_scaled_cases_lag5
data_hhs6$IAV_scaled_cases <- data_hhs6$IAV_scaled_cases_lag5
data_hhs7$IAV_scaled_cases <- data_hhs7$IAV_scaled_cases_lag5
data_hhs8$IAV_scaled_cases <- data_hhs8$IAV_scaled_cases_lag5
data_hhs9$IAV_scaled_cases <- data_hhs9$IAV_scaled_cases_lag5
data_hhs10$IAV_scaled_cases <- data_hhs10$IAV_scaled_cases_lag5

data_us$IAV_scaled_cases_smooth <- smooth_cases(data_us)
data_hhs1$IAV_scaled_cases_smooth <- smooth_cases(data_hhs1)
data_hhs2$IAV_scaled_cases_smooth <- smooth_cases(data_hhs2)
data_hhs3$IAV_scaled_cases_smooth <- smooth_cases(data_hhs3)
data_hhs4$IAV_scaled_cases_smooth <- smooth_cases(data_hhs4)
data_hhs5$IAV_scaled_cases_smooth <- smooth_cases(data_hhs5)
data_hhs6$IAV_scaled_cases_smooth <- smooth_cases(data_hhs6)
data_hhs7$IAV_scaled_cases_smooth <- smooth_cases(data_hhs7)
data_hhs8$IAV_scaled_cases_smooth <- smooth_cases(data_hhs8)
data_hhs9$IAV_scaled_cases_smooth <- smooth_cases(data_hhs9)
data_hhs10$IAV_scaled_cases_smooth <- smooth_cases(data_hhs10)
```

```{r}
n_chains <- 4 # = number of cores as well
n_warmup <- 2000
n_iter <- n_warmup + 2000

gamma <- 2 # approx 8 days for recovery
mu <- 1/80/52 # natural mortality

pop <- read.csv("Data/USA/State_2020_pop.csv")

pop_us <- sum(pop$pop_2020)

pop_HHS <- pop %>% ddply(~HHS_region, function(X){
  return(c('pop_2020'=sum(X$pop_2020)))
})
```

```{r}
data_us_stan <- data_stan(data=data_us, mu=mu, gamma=gamma, pop=pop_us)

data_hhs1_stan <- data_stan(data=data_hhs1, mu=mu, gamma=gamma, pop=pop_HHS$pop_2020[pop_HHS$HHS_region=="1"])
data_hhs2_stan <- data_stan(data=data_hhs2, mu=mu, gamma=gamma, pop=pop_HHS$pop_2020[pop_HHS$HHS_region=="2"])
data_hhs3_stan <- data_stan(data=data_hhs3, mu=mu, gamma=gamma, pop=pop_HHS$pop_2020[pop_HHS$HHS_region=="3"])
data_hhs4_stan <- data_stan(data=data_hhs4, mu=mu, gamma=gamma, pop=pop_HHS$pop_2020[pop_HHS$HHS_region=="4"])
data_hhs5_stan <- data_stan(data=data_hhs5, mu=mu, gamma=gamma, pop=pop_HHS$pop_2020[pop_HHS$HHS_region=="5"])
data_hhs6_stan <- data_stan(data=data_hhs6, mu=mu, gamma=gamma, pop=pop_HHS$pop_2020[pop_HHS$HHS_region=="6"])
data_hhs7_stan <- data_stan(data=data_hhs7, mu=mu, gamma=gamma, pop=pop_HHS$pop_2020[pop_HHS$HHS_region=="7"])
data_hhs8_stan <- data_stan(data=data_hhs8, mu=mu, gamma=gamma, pop=pop_HHS$pop_2020[pop_HHS$HHS_region=="8"])
data_hhs9_stan <- data_stan(data=data_hhs9, mu=mu, gamma=gamma, pop=pop_HHS$pop_2020[pop_HHS$HHS_region=="9"])
data_hhs10_stan <- data_stan(data=data_hhs10, mu=mu, gamma=gamma, pop=pop_HHS$pop_2020[pop_HHS$HHS_region=="10"])
```

# With viral interaction

```{r}
model <- stan_model("Fit/Stan_models/SIRS_npi_vi.stan")
parms <- c("logbeta0", "eps_beta[1]", "eps_beta[2]", "eps_beta[3]", "eps_beta[4]",
           "phi", "kappa", "omega", "rho", "S0", "I0", "sigma")
```

------- National (United States) -----------------------------------------------
  
```{r, eval=FALSE}
fit <- sampling(model, data=data_us_stan,
                chains=n_chains, iter=n_iter, warmup=n_warmup, seed=101,
                control=list(adapt_delta=0.95, max_treedepth=15),
                cores=n_chains)

saveRDS(fit, "Fit/Output/fit_RV_SIRS_npi_vi_us_lag5.RDS")
saveRDS(bridge_sampler(fit), file="Fit/Output/bridge_RV_SIRS_npi_vi_us_lag5.RDS")
```

```{r}
fit <- readRDS("Fit/Output/fit_RV_SIRS_npi_vi_us_lag5.RDS")

check_hmc_diagnostics(fit)
get_num_divergent(fit)
get_num_max_treedepth(fit)
get_low_bfmi_chains(fit)
get_bfmi(fit)

summary(fit)$summary[c(1:4,53:60),]
```

```{r}
posterior <- extract(fit)

traceplot(fit, pars=parms)
pairs(fit, pars=parms)
plot_fit(posterior, data_us)
plot_beta(posterior)
```

------- HHS 1 ------------------------------------------------------------------

```{r, eval=FALSE}
# fit <- sampling(model, data=data_hhs1_stan,
#                 chains=n_chains, iter=n_iter, warmup=n_warmup, seed=1001,
#                 control=list(adapt_delta=0.999, max_treedepth=15),
#                 cores=n_chains)
# 
# saveRDS(fit, "Fit/Output/fit_RV_SIRS_npi_vi_hhs1_lag5.RDS")
#saveRDS(bridge_sampler(fit), file="Fit/Output/bridge_RV_SIRS_npi_vi_hhs1_lag5.RDS")
```

```{r}
# fit <- readRDS("Fit/Output/fit_RV_SIRS_npi_vi_hhs1_lag5.RDS")
# 
# check_hmc_diagnostics(fit)
# get_num_divergent(fit)
# get_num_max_treedepth(fit)
# get_low_bfmi_chains(fit)
# get_bfmi(fit)
# 
# summary(fit)$summary[c(1:4,53:60),]
```

```{r}
# posterior <- extract(fit)
# 
# traceplot(fit, pars=parms)
# pairs(fit, pars=parms)
# plot_fit(posterior, data_hhs1)
# plot_beta(posterior)
```

------- HHS 2 ------------------------------------------------------------------
  
```{r, eval=FALSE}
fit <- sampling(model, data=data_hhs2_stan,
                chains=n_chains, iter=n_iter, warmup=n_warmup, seed=101,
                control=list(adapt_delta=0.95, max_treedepth=15),
                cores=n_chains)

saveRDS(fit, "Fit/Output/fit_RV_SIRS_npi_vi_hhs2_lag5.RDS")
saveRDS(bridge_sampler(fit), file="Fit/Output/bridge_RV_SIRS_npi_vi_hhs2_lag5.RDS")
```

```{r}
fit <- readRDS("Fit/Output/fit_RV_SIRS_npi_vi_hhs2_lag5.RDS")

check_hmc_diagnostics(fit)
get_num_divergent(fit)
get_num_max_treedepth(fit)
get_low_bfmi_chains(fit)
get_bfmi(fit)

summary(fit)$summary[c(1:4,53:60),]
```

```{r}
posterior <- extract(fit)

traceplot(fit, pars=parms)
pairs(fit, pars=parms)
plot_fit(posterior, data_hhs2)
plot_beta(posterior)
```

------- HHS 3 ------------------------------------------------------------------
  
```{r, eval=FALSE}
fit <- sampling(model, data=data_hhs3_stan,
                chains=n_chains, iter=n_iter, warmup=n_warmup, seed=101,
                control=list(adapt_delta=0.99, max_treedepth=15),
                cores=n_chains)

saveRDS(fit, "Fit/Output/fit_RV_SIRS_npi_vi_hhs3_lag5.RDS")
saveRDS(bridge_sampler(fit), file="Fit/Output/bridge_RV_SIRS_npi_vi_hhs3_lag5.RDS")
```

```{r}
fit <- readRDS("Fit/Output/fit_RV_SIRS_npi_vi_hhs3_lag5.RDS")

check_hmc_diagnostics(fit)
get_num_divergent(fit)
get_num_max_treedepth(fit)
get_low_bfmi_chains(fit)
get_bfmi(fit)

summary(fit)$summary[c(1:4,53:60),]
```

```{r}
posterior <- extract(fit)

traceplot(fit, pars=parms)
pairs(fit, pars=parms)
plot_fit(posterior, data_hhs3)
plot_beta(posterior)
```

------- HHS 4 ------------------------------------------------------------------
  
```{r, eval=FALSE}
fit <- sampling(model, data=data_hhs4_stan,
                chains=n_chains, iter=n_iter, warmup=n_warmup, seed=101,
                control=list(adapt_delta=0.95, max_treedepth=15),
                cores=n_chains)

saveRDS(fit, "Fit/Output/fit_RV_SIRS_npi_vi_hhs4_lag5.RDS")
saveRDS(bridge_sampler(fit), file="Fit/Output/bridge_RV_SIRS_npi_vi_hhs4_lag5.RDS")
```

```{r}
fit <- readRDS("Fit/Output/fit_RV_SIRS_npi_vi_hhs4_lag5.RDS")
  
check_hmc_diagnostics(fit)
get_num_divergent(fit)
get_num_max_treedepth(fit)
get_low_bfmi_chains(fit)
get_bfmi(fit)

summary(fit)$summary[c(1:4,53:60),]
```

```{r}
posterior <- extract(fit)

traceplot(fit, pars=parms)
pairs(fit, pars=parms)
plot_fit(posterior, data_hhs4)
plot_beta(posterior)
```

------- HHS 5 ------------------------------------------------------------------
  
```{r, eval=FALSE}
fit <- sampling(model, data=data_hhs5_stan,
                chains=n_chains, iter=n_iter, warmup=n_warmup, seed=1001,
                control=list(adapt_delta=0.95, max_treedepth=15),
                cores=n_chains)

saveRDS(fit, "Fit/Output/fit_RV_SIRS_npi_vi_hhs5_lag5.RDS")
saveRDS(bridge_sampler(fit), file="Fit/Output/bridge_RV_SIRS_npi_vi_hhs5_lag5.RDS")
```

```{r}
fit <- readRDS("Fit/Output/fit_RV_SIRS_npi_vi_hhs5_lag5.RDS")

check_hmc_diagnostics(fit)
get_num_divergent(fit)
get_num_max_treedepth(fit)
get_low_bfmi_chains(fit)
get_bfmi(fit)

summary(fit)$summary[c(1:4,53:60),]
```

```{r}
posterior <- extract(fit)

traceplot(fit, pars=parms)
pairs(fit, pars=parms)
plot_fit(posterior, data_hhs5)
plot_beta(posterior)
```

------- HHS 6 ------------------------------------------------------------------
  
```{r, eval=FALSE}
fit <- sampling(model, data=data_hhs6_stan,
                chains=n_chains, iter=n_iter, warmup=n_warmup, seed=1234,
                control=list(adapt_delta=0.95, max_treedepth=15),
                cores=n_chains)

saveRDS(fit, "Fit/Output/fit_RV_SIRS_npi_vi_hhs6_lag5.RDS")
saveRDS(bridge_sampler(fit), file="Fit/Output/bridge_RV_SIRS_npi_vi_hhs6_lag5.RDS")
```

```{r}
fit <- readRDS("Fit/Output/fit_RV_SIRS_npi_vi_hhs6_lag5.RDS")

check_hmc_diagnostics(fit)
get_num_divergent(fit)
get_num_max_treedepth(fit)
get_low_bfmi_chains(fit)
get_bfmi(fit)

summary(fit)$summary[c(1:4,53:60),]
```

```{r}
posterior <- extract(fit)

traceplot(fit, pars=parms)
pairs(fit, pars=parms)
plot_fit(posterior, data_hhs6)
plot_beta(posterior)
```

------- HHS 7 ------------------------------------------------------------------
  
```{r, eval=FALSE}
fit <- sampling(model, data=data_hhs7_stan,
                chains=n_chains, iter=n_iter, warmup=n_warmup, seed=101,
                control=list(adapt_delta=0.95, max_treedepth=15),
                cores=n_chains)

saveRDS(fit, "Fit/Output/fit_RV_SIRS_npi_vi_hhs7_lag5.RDS")
saveRDS(bridge_sampler(fit), file="Fit/Output/bridge_RV_SIRS_npi_vi_hhs7_lag5.RDS")
```

```{r}
fit <- readRDS("Fit/Output/fit_RV_SIRS_npi_vi_hhs7_lag5.RDS")

check_hmc_diagnostics(fit)
get_num_divergent(fit)
get_num_max_treedepth(fit)
get_low_bfmi_chains(fit)
get_bfmi(fit)

summary(fit)$summary[c(1:4,53:60),]
```

```{r}
posterior <- extract(fit)

traceplot(fit, pars=parms)
pairs(fit, pars=parms)
plot_fit(posterior, data_hhs7)
plot_beta(posterior)
```

------- HHS 8 ------------------------------------------------------------------
  
```{r, eval=TRUE}
fit <- sampling(model, data=data_hhs8_stan,
                chains=n_chains, iter=n_iter, warmup=n_warmup, seed=1001,
                control=list(adapt_delta=0.99, max_treedepth=15),
                cores=n_chains)

saveRDS(fit, "Fit/Output/fit_RV_SIRS_npi_vi_hhs8_lag5.RDS")
saveRDS(bridge_sampler(fit), file="Fit/Output/bridge_RV_SIRS_npi_vi_hhs8_lag5.RDS")
```

```{r}
fit <- readRDS("Fit/Output/fit_RV_SIRS_npi_vi_hhs8_lag5.RDS")

check_hmc_diagnostics(fit)
get_num_divergent(fit)
get_num_max_treedepth(fit)
get_low_bfmi_chains(fit)
get_bfmi(fit)

summary(fit)$summary[c(1:4,53:60),]
```

```{r}
posterior <- extract(fit)

traceplot(fit, pars=parms)
pairs(fit, pars=parms)
plot_fit(posterior, data_hhs8)
plot_beta(posterior)
```

------- HHS 9 ------------------------------------------------------------------
  
```{r, eval=TRUE}
fit <- sampling(model, data=data_hhs9_stan,
                chains=n_chains, iter=n_iter, warmup=n_warmup, seed=101,
                control=list(adapt_delta=0.99, max_treedepth=15),
                cores=n_chains)

saveRDS(fit, "Fit/Output/fit_RV_SIRS_npi_vi_hhs9_lag5.RDS")
saveRDS(bridge_sampler(fit), file="Fit/Output/bridge_RV_SIRS_npi_vi_hhs9_lag5.RDS")
```

```{r}
fit <- readRDS("Fit/Output/fit_RV_SIRS_npi_vi_hhs9_lag5.RDS")

check_hmc_diagnostics(fit)
get_num_divergent(fit)
get_num_max_treedepth(fit)
get_low_bfmi_chains(fit)
get_bfmi(fit)

summary(fit)$summary[c(1:4,53:60),]
```

```{r}
posterior <- extract(fit)

traceplot(fit, pars=parms)
pairs(fit, pars=parms)
plot_fit(posterior, data_hhs9)
plot_beta(posterior)
```

------- HHS 10 -----------------------------------------------------------------
  
```{r, eval=TRUE}
fit <- sampling(model, data=data_hhs10_stan,
                chains=n_chains, iter=n_iter, warmup=n_warmup, seed=101,
                control=list(adapt_delta=0.95, max_treedepth=15),
                cores=n_chains)

saveRDS(fit, "Fit/Output/fit_RV_SIRS_npi_vi_hhs10_lag5.RDS")
saveRDS(bridge_sampler(fit), file="Fit/Output/bridge_RV_SIRS_npi_vi_hhs10_lag5.RDS")
```

```{r}
fit <- readRDS("Fit/Output/fit_RV_SIRS_npi_vi_hhs10_lag5.RDS")

check_hmc_diagnostics(fit)
get_num_divergent(fit)
get_num_max_treedepth(fit)
get_low_bfmi_chains(fit)
get_bfmi(fit)

summary(fit)$summary[c(1:4,53:60),]
```

```{r}
posterior <- extract(fit)

traceplot(fit, pars=parms)
pairs(fit, pars=parms)
plot_fit(posterior, data_hhs10)
plot_beta(posterior)
```